server:
  port: 8081

postgres:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "orders"

redis:
  addr: "redis:6379"
  password: "test1234"
  # user: "user"
  db: 0
  maxRetries: 5
  dialTimeout: "10s"
  timeout: "5s"

kafka:
  brokers:
    - kafka:9092
  topic: orders